#!/usr/bin/env bash
# I&I Worldwide Website - Quick Start Script
# Run this to get started quickly!

echo "🎉 Welcome to I&I Worldwide Website!"
echo ""
echo "📍 Project Location: /Users/valentineeluwasi/Documents/GitHub/iandi"
echo ""
echo "=== QUICK START OPTIONS ==="
echo ""
echo "Option 1: View documentation in VS Code"
echo "  → Open: DOCUMENTATION_INDEX.md"
echo "  → Then read: QUICK_START.md"
echo ""
echo "Option 2: Start the development server"
echo "  → Run: npm run dev"
echo "  → Visit: http://localhost:3000"
echo ""
echo "Option 3: Update website content"
echo "  → Open: lib/content.ts"
echo "  → Edit the text (no coding needed)"
echo "  → Save and refresh browser"
echo ""
echo "Option 4: Prepare for launch"
echo "  → Read: LAUNCH_CHECKLIST.md"
echo "  → Follow the checklist"
echo ""
echo "=== IMPORTANT FILES ==="
echo "├── 📖 DOCUMENTATION_INDEX.md    ← Navigation guide (START HERE)"
echo "├── 🚀 QUICK_START.md            ← Quick start guide"
echo "├── ✏️  CMS_GUIDE.md              ← How to update content"
echo "├── 📋 LAUNCH_CHECKLIST.md       ← Before going live"
echo "├── 📚 README.md                 ← Full documentation"
echo "├── 💻 README_WEBSITE.md         ← Technical details"
echo "└── 📝 lib/content.ts            ← ALL WEBSITE TEXT"
echo ""
echo "=== QUICK COMMANDS ==="
echo "npm run dev              → Start development server"
echo "npm run build            → Create production build"
echo "npm start                → Start production server"
echo ""
echo "=== 5-MINUTE SETUP ==="
echo "1. Read: DOCUMENTATION_INDEX.md (1 min)"
echo "2. Run: npm run dev (1 min)"
echo "3. Open: lib/content.ts (1 min)"
echo "4. Edit some text (1 min)"
echo "5. Refresh browser and see changes (1 min)"
echo ""
echo "=== DEPLOY TO LIVE WEB ==="
echo "1. Read: LAUNCH_CHECKLIST.md"
echo "2. Install: npm install -g vercel"
echo "3. Deploy: vercel"
echo ""
echo "✅ Your website is ready!"
echo "📖 Start with: DOCUMENTATION_INDEX.md"
echo ""
